### ISSUE TITLE
Front-end layout

### ISSUE THREAD

**Issue by tpmccauley** [KonVas/Ipsosboard#7]
I am wondering if using something like bootstrap (or something else?) for layout wouldn't a) be desirable, b) do-able by next week

Advantages include responsive layout (adjusting for different devices), nice components like sliders, buttons, etc. and the fact that I have experience with it

https://getbootstrap.com/

**Comment by KonVas** [comment]
Yes, do you think that would make easier to use for the tables' layout, cause right now I think there is a bug (mentioned [here](https://github.com/KonVas/Ipsosboard/issues/2)) could this be avoided with bootstrap maybe.

**Comment by muellmusik** [comment]
> I am wondering if using something like bootstrap (or something else?) for layout wouldn't a) be desirable, b) do-able by next week

Well, I guess this may depend on you Tom. TBH, I'm not that familiar with either, so it may depend on how much of this you want to take on. At the moment we something that's more than 50% there, so we could just try to get that together. On the other hand, if you think you can knock it out quickly on bootstrap, then maybe it's better.

Deployment for next week is also a question.

**Comment by tpmccauley** [comment]
I will spend a bit of time seeing how far I get. In-principle it should be quick to knock out. If it turns to not be the case, then I will cut my losses.

**Comment by tpmccauley** [comment]
<img width="1150" alt="screen shot 2018-04-05 at 11 48 33 am" src="https://user-images.githubusercontent.com/496503/38362388-9871989a-38c8-11e8-89c0-f320d48877fd.png">

**Comment by muellmusik** [comment]
Looks nice!

**Comment by KonVas** [comment]
Just a minor think. Should we leave the beer logo or move it somewhere at the bottom. I think it's a bit too obvious and takes focus away from the main interface and the rest of the page. Should we put it somewhere more inconspicuous.

**Comment by muellmusik** [comment]
Sure, but I’m more concerned about functionality. Cosmetics low priority for next week I’d say.
