### ISSUE TITLE
Argument 3 of AudioParam.setTargetAtTime is not a finite floating-point value.

### ISSUE THREAD

**Issue by KonVas** [KonVas/Ipsosboard#8]
I think this has to do with the arguments of this method `synth.triggerAttackRelease({duration: "4n", velocity: 1 / instance.synthArray.length});` to initiate the synth. I am looking on this now.

**Comment by muellmusik** [comment]
Thanks. We're driving back today. If you could have a go that would be great.

**Comment by KonVas** [comment]
Okay, I think I found what was causing the problem of not a finite floating point value. Now, however, I see the disposition method is creating something that I am not sure if this is really a problem or the proper way of working, in any case whenever I press play again after playing something I get this error: 
> TypeError: synth.dispose is not a function

Is this something that needs to be used. AFAIU this cleans up any previous synth running in the interface right? Does this make any sense (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_a_function) [i.e. **Function called on the wrong object**]

**Comment by muellmusik** [comment]
Yes. It probably means the for loop is accessing the index rather than the value. Have to remember this in js.

**Comment by muellmusik** [comment]
Yes, should be:

for (var s in instance.synthArray) {
              instance[s].dispose();
            }

Sorry

**Comment by KonVas** [comment]
Okay, I pushed some changes. Synths are controlled now, not sure about 'detune' parameter, can check later again. I have commented out this `for (var s in instance.synthArray) { instance[s].dispose(); }` ->
> TypeError: instance[s] is undefined

**Comment by muellmusik** [comment]
Sorry should be instance.synthArray[s]

Doing this from my phone...
